version: 0.0
os: linux
files:
  - source: ./play-scala-0.1.0-SNAPSHOT.zip
    destination: /tmp
hooks:
  ApplicationStop:
    - location: scripts/StopApplication.sh
      timeout: 120
  BeforeInstall:
    - location: scripts/CleanOldArtifact.sh
      timeout: 120
  AfterInstall:
    - location: scripts/UnpackNewArtifact.sh
      timeout: 120
  ApplicationStart:
    - location: scripts/StartApplication.sh
      timeout: 120